source 'ssh://git@git.innerfunction.com:22222/julian/if-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'project.xcworkspace'
target 'Pushover' do
    pod 'GRMustache', '~> 7.3.2'
    pod 'SCFFLD'
    pod 'Q'
end

